import Link from "next/link";
import FooterFreeTools from "@/components/FooterFreeTools";
const title="Free Student Study Kit: Revision Planner and Flashcard Checklist";
const description="Download free weekly revision, practice-question error log and flashcard-checking templates. No account needed; use them with any study app.";
const url="https://forksai.app/resources/student-study-kit";
export const metadata={title,description,alternates:{canonical:url},openGraph:{type:"website",title,description,url,images:[{url:"/body.png",width:1200,height:630}]},twitter:{card:"summary_large_image",title,description,images:["/body.png"]}};
const resources=[{name:"Weekly revision planner",file:"weekly-revision-planner.txt",text:"List course objectives, estimate the time available, and choose a specific recall task and application exercise for each session."},{name:"Practice-question error log",file:"practice-question-error-log.txt",text:"Record what went wrong, check the explanation against your source, and choose a targeted follow-up rather than repeating the same mistake."},{name:"Flashcard quality checklist",file:"flashcard-quality-checklist.txt",text:"Check that each card asks one clear question, has a verified answer, and adds something useful to your deck."}];
export default function Page(){return <>
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify([{"@context":"https://schema.org","@type":"WebPage",name:title,description,url,dateModified:"2026-09-16",publisher:{"@type":"Organization",name:"FORKSAI",url:"https://forksai.app"}},{"@context":"https://schema.org","@type":"BreadcrumbList",itemListElement:[{"@type":"ListItem",position:1,name:"Home",item:"https://forksai.app"},{"@type":"ListItem",position:2,name:"Student study kit",item:url}]}])}}/>
 <header className="border-b-2 border-black px-6 py-5"><Link href="/" className="text-xl font-bold">FORKSAI</Link></header>
 <main className="max-w-4xl mx-auto px-6 py-14">
  <nav aria-label="Breadcrumb" className="text-sm mb-8"><Link href="/" className="underline">Home</Link> / Student study kit</nav>
  <h1 className="text-4xl sm:text-5xl font-extrabold mb-6">Free student study kit</h1>
  <p className="text-lg leading-relaxed mb-6">Three reusable templates for planning revision, learning from practice questions, and checking flashcards. Download them without an account and use them with FORKSAI, another app, or a paper notebook.</p>
  <section aria-label="Download study templates" className="grid sm:grid-cols-3 gap-5 my-10">{resources.map(r=><div key={r.file} className="border-2 border-black rounded-xl p-5 bg-white"><h2 className="font-bold text-xl mb-3">{r.name}</h2><p className="leading-relaxed mb-4">{r.text}</p><a download href={"/resources/"+r.file} className="underline font-bold">Download text template</a></div>)}</section>
  <section className="mt-12"><h2 className="text-2xl font-bold mb-4">How to use the kit</h2><ol className="list-decimal pl-6 space-y-4"><li>Choose the learning objectives and source material for one course. Fill in the planner with realistic time blocks around classes, work and rest.</li><li>For each session, choose a task you can check: answer a short set of cards without looking, solve a problem, or draft an essay plan. Reading can help you prepare, but include a task that tests understanding.</li><li>Record mistakes in the error log. Check the relevant explanation in your course sources, then decide whether you need a clearer card, more concept work, or another application exercise.</li><li>Use the quality checklist before adding cards. Fix unclear questions and unverified answers, and remove duplicates when your review load becomes difficult to finish.</li></ol></section>
  <section className="mt-12"><h2 className="text-2xl font-bold mb-4">A worked planning example</h2><p className="leading-relaxed mb-4">Suppose you have 45 minutes to revise a biology lecture. You might spend 10 minutes checking the objectives and confusing points, 15 minutes retrieving answers from a small deck, 15 minutes working through a course question, and 5 minutes recording what to revisit. This is an editable example, not a prescribed or scientifically optimal timing formula.</p><p className="leading-relaxed">In the error log, avoid a note like “bad at biology.” Write the specific gap, such as “could define the process but could not explain the effect of changing one stage.” Record the source section to revisit and a concrete follow-up task.</p></section>
  <section className="mt-12"><h2 className="text-2xl font-bold mb-4">Choose tools for your course</h2><ul className="space-y-3"><li><Link href="/pdf-to-flashcards" className="underline">Create an editable deck from lecture PDFs</Link></li><li><Link href="/attendance-calculator" className="underline">Check attendance against your course requirement</Link></li><li><Link href="/negative-marking-calculator" className="underline">Estimate an exam score under your marking scheme</Link></li><li><Link href="/for/university-students" className="underline">University study workflow</Link></li><li><Link href="/for/high-school-students" className="underline">High school revision workflow</Link></li><li><Link href="/for/medical-students" className="underline">Medical student review workflow</Link></li></ul></section>
  <section className="mt-12"><h2 className="text-2xl font-bold mb-4">For teachers, tutors and student societies</h2><p className="leading-relaxed">These templates were authored by the FORKSAI team and are free to copy, adapt and redistribute, including in class handouts. You can share this page with students; attribution is appreciated but not required. No university affiliation or endorsement is implied.</p></section>
  <section className="mt-12"><h2 className="text-2xl font-bold mb-4">Further reading</h2><p className="leading-relaxed mb-4">The templates are our own planning aids. For guidance on active study and spreading practice across sessions, read <a href="https://learningcenter.unc.edu/tips-and-tools/studying-101-study-smarter-not-harder/" className="underline">UNC Chapel Hill’s Studying 101 guide</a>. Dartmouth also publishes an <a href="https://students.dartmouth.edu/academic-skills/learning-resources/academic-resource-library" className="underline">academic resource library</a> with study worksheets.</p><p className="text-sm">Published September 16, 2026 · FORKSAI Team</p></section>
 </main><footer className="bg-black text-white px-6"><div className="max-w-6xl mx-auto"><FooterFreeTools/></div></footer>
 </>;}
