"use client";

import { useState } from "react";
import { motion } from "framer-motion";
import { Shield, Menu, X } from "lucide-react";
import { dmSerifDisplay, dmSans } from "@/lib/fonts";

/* ── Section data ── */
const sections = [
  {
    id: "scope",
    title: "Scope & Definitions",
    content: (
      <>
        <p>
          This Privacy Policy applies to your use of <strong>FORKSAI</strong> - including all related services, APIs, the study dashboard, flashcard tools, PDF summarizer, PDF-to-Notes, quiz generator, revision and study modes, streak tracking, achievements, and any content or data you generate or interact with on our platform.
        </p>
        <div className="mt-5 border border-white/8 rounded-xl p-5 bg-white/2">
          <p className="text-xs uppercase tracking-widest text-zinc-500 mb-3">Key terms</p>
          <ul className="space-y-3 text-sm text-zinc-400">
            {[
              ["Personal Data", "Information that identifies or can identify an individual - such as name, email address, or account identifiers."],
              ["Content Data", "Inputs you provide (text, PDFs, study prompts, uploads) and outputs generated by FORKSAI tools (flashcards, summaries, quiz questions, etc.)."],
              ["Usage Data", "Logs, feature activity (e.g. flashcard sessions, summarizer usage, study timer sessions), timestamps, streaks, and device/browser metadata."],
              ["Study Session Data", "Records of your study timer sessions including start time, end time, and calculated study duration stored per user account."],
              ["Database Records", "User-generated content and history securely stored - including flashcard decks, summaries, quiz results, goals, and achievements."],
              ["Cookies", "Small files stored on your device for authentication, session management, and analytics."],
            ].map(([term, def]) => (
              <li key={term} className="flex gap-3">
                <span className="font-medium text-white shrink-0 w-36">{term}</span>
                <span>{def}</span>
              </li>
            ))}
          </ul>
        </div>
      </>
    ),
  },
  {
    id: "personal-data",
    title: "Personal Data We Collect",
    content: (
      <ul className="space-y-4 text-sm text-zinc-400">
        {[
          ["Account & Profile Data", "Your name, email address, profile photo (if signing in via Google), and authentication tokens."],
          ["Authentication Emails", "Your email address used to send verification links, password reset emails, and essential account security notifications."],
          ["Study Session Data", "Start time, end time, and duration of each study timer session - used to calculate daily and weekly study totals shown on your dashboard."],
          ["Flashcard & Deck Data", "All flashcard decks you create - whether AI-generated or manual - including card content, deck titles, creation timestamps, and source type."],
          ["Study Streak & Activity Data", "Daily activity logs used to calculate your study streak, heatmap, and consistency statistics shown in your dashboard."],
          ["Goal Data", "Study goals you create during sessions, stored temporarily in your session and not permanently retained after logout."],
          ["Achievement Data", "Records of achievements unlocked based on your activity - stored per account to persist across sessions."],
          ["Subscription & Billing Data", "Subscription status, plan type (free or premium), billing cycle, transaction identifiers, and payment confirmation timestamps. Card details are never stored on our servers."],
          ["Content Data", "Text you provide and the text extracted in your browser from PDFs you select, which is sent to our AI tools (PDF Summarizer, PDF-to-Notes, AI Flashcard Generator), and the outputs generated from them. The original PDF file is not uploaded to our servers."],
          ["Usage & Device Data", "Feature activity, session logs, IP address, operating system, browser type, and device identifiers."],
          ["Cookies & Analytics", "Used to maintain sessions, measure engagement, and improve platform performance."],
        ].map(([term, def]) => (
          <li key={term} className="flex gap-3 border-b border-white/4 pb-4 last:border-0 last:pb-0">
            <span className="font-medium text-white shrink-0 w-48">{term}</span>
            <span>{def}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "usage",
    title: "How We Use Your Data",
    content: (
      <>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            "To provide and operate the FORKSAI platform - including flashcard creation (AI and manual), PDF summarization, quiz generation, all revision modes (Memory Sprint, Spaced Repetition, Weak Spot Trainer, Pomodoro, AI Revision, Exam Simulator, Explain Back), activity heatmap, Explore Decks feature, and the study dashboard.",
            "To calculate and display study statistics - including daily study time, weekly totals, streaks, activity heatmap calendar view (showing daily consistency patterns), and consistency percentages.",
            "To manage and display your achievements and progress, unlocked based on your real activity across the platform.",
            "To manage Premium subscriptions - verifying payment status and enabling or restricting access to paid AI features.",
            "To store and retrieve your flashcard decks and summaries across sessions and devices.",
            "To authenticate your account securely, verify email addresses, and facilitate password recovery.",
            "To analyze platform performance, debug issues, and improve AI output quality.",
            "To personalize your experience across sessions using your stored preferences and activity history.",
            "To send product updates, security notifications, and optional communications.",
            "To ensure platform security, prevent fraud, and comply with legal requirements.",
          ].map((text, i) => (
            <li key={i} className="flex gap-3 text-sm">
              <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
              <span>{text}</span>
            </li>
          ))}
        </ul>
        <div className="mt-5 px-4 py-3 rounded-xl border border-white/8 bg-white/2 text-xs text-zinc-500">
          <strong className="text-zinc-300">Legal basis:</strong> consent, contractual necessity, legitimate interests, or compliance with legal obligations - depending on the processing activity.
        </div>
      </>
    ),
  },
  {
    id: "study-timer",
    title: "Study Timer & Session Tracking",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          FORKSAI includes a built-in study timer that tracks your focus sessions. When you start and stop the timer, the session start time, end time, and calculated duration are recorded and sent to our servers.
        </p>
        <ul className="mt-4 space-y-3 text-sm text-zinc-400">
          {[
            "Study session data is stored per user account and used to calculate your daily and weekly study totals shown on the dashboard.",
            "If you close your browser or tab without stopping the timer, the session may not be recorded. We recommend stopping the timer before logging out.",
            "Study time is used solely to power your personal statistics - it is never shared with third parties or used for advertising.",
            "You may request deletion of your study history as part of a full account deletion request.",
          ].map((t, i) => (
            <li key={i} className="flex gap-3">
              <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
              <span>{t}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "flashcards",
    title: "Flashcard & AI Tool Data",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          FORKSAI allows you to create flashcard decks either manually or using AI generation from uploaded PDFs or text. This section explains how that data is handled.
        </p>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            "Flashcard decks - including their content, titles, creation dates, and source type (AI or manual) - are stored securely in your account and accessible only to you.",
            "When using AI Flashcard generation, your input text or PDF content is temporarily processed by our AI services to generate card content. This input is not stored permanently or used to train public models.",
            "For PDFs, the text is extracted in your browser and only that text is sent for processing - the original PDF file is not uploaded to or stored on our servers. The extracted text is processed transiently to generate your flashcards, notes, or summary and is not retained after processing.",
            "Quiz questions generated from your material are produced on-demand and not stored unless you explicitly save them.",
            "You may delete individual flashcards, entire decks, or summaries at any time from within the dashboard.",
            "Deleted content is removed from active systems immediately, though encrypted backups may retain it briefly for security purposes.",
          ].map((t, i) => (
            <li key={i} className="flex gap-3">
              <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
              <span>{t}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "achievements",
    title: "Achievements & Streaks",
    content: (
      <p className="text-sm text-zinc-400 leading-relaxed">
        FORKSAI tracks your study activity to calculate streaks, unlock achievements, and display consistency statistics. This data - including daily active days, streak counts, and achievement milestones - is stored per account and used only to power your personal dashboard. It is never shared with other users or used for any advertising purpose. Streak data is derived from your flashcard creation and study session activity timestamps.
      </p>
    ),
  },
  {
    id: "goals",
    title: "Study Goals",
    content: (
      <p className="text-sm text-zinc-400 leading-relaxed">
        Study goals you create during a session are stored temporarily in your browser's session storage. They are not sent to our servers or retained after you close the tab or log out. Additional goal slots are unlocked based on your accumulated study time during a session - this calculation is performed client-side. No goal content is associated with your account permanently.
      </p>
    ),
  },
  {
    id: "payments",
    title: "Premium Subscriptions & Payments",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          FORKSAI offers optional Premium subscription plans that unlock AI-powered features including unlimited flashcard generation, PDF summarization, and all revision modes.
        </p>
        <ul className="mt-4 space-y-3 text-sm text-zinc-400">
          {[
            "Payments are processed securely through our third-party payment provider, Dodo Payments.",
            "We do not collect or store your full payment card numbers, CVV codes, or banking credentials on our servers.",
            "Payment-related data such as transaction IDs, subscription status, plan type, billing cycle, and payment confirmation timestamps may be stored for access control, accounting, and support.",
            "All payment processing is handled directly by Dodo Payments under their own privacy and security policies.",
            "Premium status is verified on each request to determine whether AI features should be accessible or restricted.",
          ].map((t, i) => (
            <li key={i} className="flex gap-3">
              <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
              <span>{t}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "billing-support",
    title: "Billing, Cancellations & Refunds",
    content: (
      <p className="text-sm text-zinc-400 leading-relaxed">
        Users can manage or cancel their Premium subscription according to the terms presented at the time of purchase. Billing inquiries, payment failures, or refund-related questions can be directed to our support team at <a href="mailto:support@forksai.app" className="text-[#b5ff4d] hover:underline underline-offset-4">support@forksai.app</a>. Refund eligibility may depend on the payment provider's policies and the plan selected.
      </p>
    ),
  },
  {
    id: "retention",
    title: "Retention & Deletion",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          We retain personal and content data only as long as required to provide services or comply with legal obligations.
        </p>
        <ul className="mt-4 space-y-3 text-sm text-zinc-400">
          {[
            ["Account data", "Retained until the user deletes their account, with limited backup retention."],
            ["Flashcard decks & summaries", "Stored until manually deleted by the user or removed as part of account deletion."],
            ["Study session records", "Retained to power your dashboard statistics. Deleted upon account deletion request."],
            ["Streak & achievement data", "Retained per account to persist across sessions. Deleted upon account deletion."],
            ["Goal data", "Session-only. Not stored on servers. Cleared when the browser tab is closed."],
            ["Logs & temporary data", "Retained for 30–90 days for debugging and performance monitoring."],
            ["Backups", "Securely stored and not publicly accessible. Purged on a rolling schedule."],
          ].map(([term, def]) => (
            <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
              <span className="font-medium text-white shrink-0 w-48">{term}</span>
              <span>{def}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "sharing",
    title: "Sharing & Disclosure",
    content: (
      <ul className="space-y-3 text-sm text-zinc-400">
        {[
          ["Service providers", "Cloud hosting, analytics, email systems, authentication providers, and payment processors (Dodo Payments) - all operating under strict security and compliance standards."],
          ["Legal compliance", "When required by law, regulation, or valid legal process."],
          ["Business transfers", "In the event of a merger, acquisition, or restructuring, data may be transferred as part of that transaction."],
          ["User consent", "Data is shared with third parties beyond those listed above only with your explicit permission."],
        ].map(([term, def]) => (
          <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
            <span className="font-medium text-white shrink-0 w-36">{term}</span>
            <span>{def}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "security",
    title: "Security Measures",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          We employ multiple layers of technical and organizational security to protect your data.
        </p>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            "Database encryption and access control for all stored user data including flashcards, summaries, and session records.",
            "Encryption in transit (HTTPS) for all data exchanged between your browser and our servers.",
            "Secure authentication using token-based access, email verification, and password recovery flows.",
            "Trusted third-party authentication providers for sign-in and account protection.",
            "Firebase security rules to ensure users can only access their own data.",
            "Regular backups, monitoring, and vulnerability reviews.",
          ].map((t, i) => (
            <li key={i} className="flex gap-3">
              <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
              <span>{t}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "auth",
    title: "Account & Authentication",
    content: (
      <ul className="space-y-3 text-sm text-zinc-400">
        {[
          "FORKSAI uses Google Sign-In (Google OAuth) as its sole authentication method. We do not operate our own password system and never see or store your Google password.",
          "When you sign in, Google shares basic profile information with us - typically your name, email address, and profile photo - which we use to create and secure your account.",
          "Authentication is handled by Firebase Authentication (Google) using secure, token-based, industry-standard practices.",
          "Authentication data is used solely to provide secure access to the platform and is never shared publicly or sold.",
        ].map((t, i) => (
          <li key={i} className="flex gap-3">
            <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
            <span>{t}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "cookies",
    title: "Cookies & Tracking",
    content: (
      <ul className="space-y-3 text-sm text-zinc-400">
        {[
          "Session cookies for authentication and maintaining your logged-in state across the dashboard.",
          "Analytics cookies to monitor feature usage, study tool engagement, and platform performance.",
          "Preference cookies for saving user settings.",
          "You can disable cookies via your browser settings, though some functionality - including staying logged in - may be limited.",
        ].map((t, i) => (
          <li key={i} className="flex gap-3">
            <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
            <span>{t}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "children",
    title: "Children's Privacy",
    content: (
      <p className="text-sm text-zinc-400 leading-relaxed">
        FORKSAI is not intended for users under 13 (or the applicable minimum age in your jurisdiction). We do not knowingly collect or store data from minors. If we become aware of such collection, we delete it promptly. If you believe a minor has created an account, please contact us at <a href="mailto:support@forksai.app" className="text-[#b5ff4d] hover:underline underline-offset-4">support@forksai.app</a>.
      </p>
    ),
  },
  {
    id: "transfers",
    title: "International Data Transfers",
    content: (
      <p className="text-sm text-zinc-400 leading-relaxed">
        Your data may be processed and stored on servers located outside your country or region. All transfers follow appropriate safeguards - such as standard contractual clauses or equivalent mechanisms - to protect your rights and data.
      </p>
    ),
  },
  {
    id: "rights",
    title: "Your Rights",
    content: (
      <ul className="space-y-3 text-sm text-zinc-400">
        {[
          ["Access", "Request a copy of the data we store about you, including flashcard history, study session records, and account data."],
          ["Correction", "Update or correct inaccurate information in your account."],
          ["Deletion", "Request permanent deletion of your account and all associated data - including flashcard decks, summaries, study sessions, streaks, and achievements."],
          ["Restriction", "Restrict or object to certain types of processing, such as analytics tracking."],
          ["Consent withdrawal", "Withdraw consent for optional features like marketing communications at any time."],
          ["Data portability", "Request an export of your content and activity data where technically feasible."],
        ].map(([term, def]) => (
          <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
            <span className="font-medium text-white shrink-0 w-28">{term}</span>
            <span>{def}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "regional-rights",
    title: "Region-Specific Rights",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          Depending on where you live, you may have additional rights. We honor these rights for all users where they apply. To exercise any of them, email <a href="mailto:support@forksai.app" className="text-[#b5ff4d] hover:underline underline-offset-4">support@forksai.app</a> from your account email; we may need to verify your identity before acting on a request, and we will respond within the timeframe required by applicable law.
        </p>
        <div className="space-y-4 text-sm text-zinc-400">
          <div>
            <p className="font-medium text-white mb-1">India - Digital Personal Data Protection Act, 2023 (DPDP)</p>
            <p className="leading-relaxed">
              If you are in India, you have the right to access, correct, complete, update, and erase your personal data, to nominate another person to exercise your rights in the event of death or incapacity, and to grievance redressal. You may withdraw consent at any time. Concerns may be raised with our Grievance Officer (below), and you may escalate unresolved complaints to the Data Protection Board of India.
            </p>
          </div>
          <div>
            <p className="font-medium text-white mb-1">EU / UK - GDPR</p>
            <p className="leading-relaxed">
              If you are in the European Economic Area, United Kingdom, or Switzerland, you have the rights of access, rectification, erasure ("right to be forgotten"), restriction of processing, data portability, and objection to processing, and the right not to be subject to solely automated decisions with legal effects. Where we rely on consent, you may withdraw it at any time without affecting prior processing. You also have the right to lodge a complaint with your local data protection authority. Our legal bases for processing are performance of our contract with you, your consent, our legitimate interests in operating and securing the Service, and compliance with legal obligations.
            </p>
          </div>
          <div>
            <p className="font-medium text-white mb-1">California - CCPA / CPRA</p>
            <p className="leading-relaxed">
              If you are a California resident, you have the right to know what personal information we collect and how it is used and shared, to request deletion or correction of your personal information, and to be free from discrimination for exercising your rights. <strong className="text-white">We do not sell or share your personal information</strong> for cross-context behavioral advertising, and we do not use sensitive personal information for purposes beyond providing the Service.
            </p>
          </div>
        </div>
      </>
    ),
  },
  {
    id: "grievance",
    title: "Data Controller & Grievance Officer",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          FORKSAI is the data controller responsible for your personal data. If you have any questions, complaints, or requests regarding your personal data or this Privacy Policy - including requests to access or delete your data - you can contact our Grievance Officer:
        </p>
        <p className="mt-3 text-sm">
          <a href="mailto:support@forksai.app" className="text-[#b5ff4d] hover:underline underline-offset-4 font-medium">support@forksai.app</a>
        </p>
        <p className="mt-3 text-xs text-zinc-600 leading-relaxed">
          We acknowledge grievances promptly and aim to resolve them within the timeframe required by applicable law. This Privacy Policy is governed by the laws of India, without prejudice to any mandatory data-protection rights you hold under the laws of your country of residence.
        </p>
      </>
    ),
  },
  {
    id: "third-parties",
    title: "Third-Party Services",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          FORKSAI uses third-party services to power certain features. These providers process data under their own privacy policies.
        </p>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            ["Firebase (Google)", "Authentication, real-time database, and secure storage for user accounts, flashcard decks, study sessions, and achievements."],
            ["AI & processing APIs", "Large language model providers used for flashcard generation, PDF summarization, and quiz creation. Input is processed transiently and not used to train public models."],
            ["Dodo Payments", "Secure payment processing for Premium subscriptions."],
            ["Vercel Speed Insights", "Performance monitoring to measure page load times and platform reliability."],
            ["Analytics tools", "Aggregated usage data to understand feature engagement and improve the platform."],
          ].map(([term, def]) => (
            <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
              <span className="font-medium text-white shrink-0 w-40">{term}</span>
              <span>{def}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "public-decks-privacy",
    title: "Public Decks & Data Privacy",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          FORKSAI allows users to share AI-generated flashcard decks publicly through the Explore library. <strong className="text-white">Your privacy is protected: only flashcard content is shared publicly - never your personal account information.</strong>
        </p>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            ["What is shared when a deck is public", "Only the flashcard deck content (questions, answers, and deck title) is visible to other users in the Explore library."],
            ["What is NOT shared", "Your email address, account creation date, subscription status, account settings, and any other personal account information are never exposed publicly. Your identity on the platform is represented by your account name only."],
            ["Creator attribution", "Your account name appears as the deck creator for attribution purposes. This allows other users to recognize quality decks and discover more from the same creator - but does not expose any personal data beyond the name you chose."],
            ["Control over sharing", "You can toggle any AI-generated deck between public and private at any time via deck settings. Making a deck private immediately removes it from public search and hides it from other users."],
            ["Account deletion removes public decks", "If you delete your account, all your public decks are removed from the Explore library. Other users who imported your decks retain their private copies, but the public deck is no longer discoverable."],
            ["Safe to share", "You can confidently make decks public knowing that your email, personal information, and account details remain completely private. Only flashcard content is visible."],
          ].map(([term, def]) => (
            <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
              <span className="font-medium text-white shrink-0 w-48">{term}</span>
              <span>{def}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "gifted-premium",
    title: "Gifted Premium Monitoring",
    content: (
      <ul className="space-y-3 text-sm text-zinc-400">
        {[
          "If you are granted a gifted Premium account by FORKSAI, we may monitor your platform usage to ensure compliance with our policies.",
          "We collect usage data, prompt activity, and feature engagement to identify any potential abuse, suspicious activity, or violation of our terms.",
          "In the event of anomalous activity, FORKSAI reserves the right to process this data to investigate and subsequently suspend or revoke the gifted access without prior notice.",
          "Data associated with a suspended gifted account will be retained in accordance with our standard retention policies for security and audit purposes."
        ].map((t, i) => (
          <li key={i} className="flex gap-3">
            <span className="text-[#b5ff4d] shrink-0 mt-0.5">-</span>
            <span>{t}</span>
          </li>
        ))}
      </ul>
    ),
  },
  {
    id: "study-rooms",
    title: "Study Rooms",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed mb-4">
          FORKSAI Study Rooms are real-time multiplayer study sessions where a host and participants study a shared flashcard deck together. This section explains how data is handled within Study Rooms.
        </p>
        <ul className="space-y-3 text-sm text-zinc-400">
          {[
            ["Room data collected", "When a Study Room is created, FORKSAI stores: the room code, host user ID, deck title and cards, session settings (mode, answer mode, break type), participant list (user IDs and display names), card progress for each participant, and chat messages sent during the session."],
            ["Data is ephemeral", "All Study Room data is stored temporarily in our database and expires automatically 2 hours after the room is created. No Study Room data is retained beyond this window."],
            ["Chat messages", "Messages sent in the Study Room chat are visible to all current participants and stored within the room document until it expires. Chat history is not permanently recorded or associated with any user account after expiry."],
            ["Participant visibility", "When you join a Study Room, your display name is visible to other participants for the duration of the session. Your email address and other account details are never shared."],
            ["Session progress", "Card answers and completion progress within a session are tracked per participant to power live leaderboards in race mode. This data is discarded with the room on expiry."],
            ["No long-term retention", "Study Room activity does not contribute to your personal study statistics, streaks, or heatmap. Room data is entirely session-scoped and automatically deleted."],
          ].map(([term, def]) => (
            <li key={term} className="flex gap-3 border-b border-white/4 pb-3 last:border-0 last:pb-0">
              <span className="font-medium text-white shrink-0 w-48">{term}</span>
              <span>{def}</span>
            </li>
          ))}
        </ul>
      </>
    ),
  },
  {
    id: "changes",
    title: "Changes to This Policy",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          We may update this Privacy Policy from time to time to reflect product changes, new features, or legal requirements. Major updates will be communicated through in-app notifications, email, or website banners. The most recent revision date will always appear at the top of this page.
        </p>
        <p className="mt-3 text-xs text-zinc-600 italic">Last updated: June 9, 2026 (v12.1)</p>
      </>
    ),
  },
  {
    id: "contact",
    title: "Contact Us",
    content: (
      <>
        <p className="text-sm text-zinc-400 leading-relaxed">
          For questions, concerns, or data-related requests regarding FORKSAI, contact us at:
        </p>
        <p className="mt-3">
          <a href="mailto:support@forksai.app" className="text-[#b5ff4d] hover:underline underline-offset-4 text-sm font-medium">
            support@forksai.app
          </a>
        </p>
        <p className="mt-3 text-xs text-zinc-600">
          We aim to respond to privacy-related inquiries within 7 business days.
        </p>
      </>
    ),
  },
];

/* ── Component ── */
export default function PrivacyPolicyContent() {
  const [navOpen, setNavOpen] = useState(false);

  return (
    <div
      className={`${dmSans.variable} ${dmSerifDisplay.variable} min-h-screen bg-[#080808] text-zinc-100`}
      style={{ fontFamily: "var(--font-dm-sans), sans-serif" }}
    >
      {/* grain */}
      <div className="fixed inset-0 pointer-events-none z-0 opacity-[0.025]"
        style={{ backgroundImage: `url("data:image/svg+xml,%3Csvg viewBox='0 0 200 200' xmlns='http://www.w3.org/2000/svg'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.85' numOctaves='4' stitchTiles='stitch'/%3E%3C/filter%3E%3Crect width='100%25' height='100%25' filter='url(%23n)'/%3E%3C/svg%3E")`, backgroundSize: "160px" }} />

      {/* ── HEADER ── */}
      <header className="fixed top-0 inset-x-0 z-40 bg-[#080808]/90 backdrop-blur-md border-b border-white/6">
        <div className="max-w-6xl mx-auto px-6 py-4 flex items-center justify-between">
          <a href="/" className="flex items-center gap-2.5">
            <img src="/forks-logo.png" alt="FORKSAI" className="h-6 w-auto" />
            <div>
              <p className="text-xs font-bold tracking-[0.2em] uppercase leading-none">FORKSAI</p>
              <p className="text-[9px] uppercase tracking-widest text-zinc-600 mt-0.5">Privacy Policy</p>
            </div>
          </a>

          <nav className="hidden md:flex items-center gap-6 text-xs">
            <a href="/" className="text-zinc-500 hover:text-white transition-colors">← Back home</a>
            <a href="/docs" className="text-zinc-500 hover:text-white transition-colors">Docs</a>
            <span className="text-[#b5ff4d] font-medium">Privacy</span>
            <a href="/terms" className="text-zinc-500 hover:text-white transition-colors">Terms</a>
          </nav>

          <button onClick={() => setNavOpen(v => !v)} className="md:hidden p-1.5 border border-white/8 rounded-lg text-zinc-400">
            {navOpen ? <X size={16} /> : <Menu size={16} />}
          </button>
        </div>

        {navOpen && (
          <div className="md:hidden border-t border-white/6 bg-[#080808]">
            <div className="px-6 py-4 flex flex-col gap-3 text-sm">
              <a href="/" onClick={() => setNavOpen(false)} className="text-zinc-400 hover:text-white transition-colors">← Back home</a>
              <a href="/docs" onClick={() => setNavOpen(false)} className="text-zinc-400 hover:text-white transition-colors">Docs</a>
              <span className="text-[#b5ff4d] font-medium">Privacy Policy</span>
              <a href="/terms" onClick={() => setNavOpen(false)} className="text-zinc-400 hover:text-white transition-colors">Terms & Conditions</a>
            </div>
          </div>
        )}
      </header>

      {/* ── MAIN ── */}
      <main className="relative z-10 pt-24">
        <div className="max-w-6xl mx-auto px-6 md:px-12 py-12">

          {/* Page header */}
          <motion.div
            initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}
            className="mb-14"
          >
            <div className="inline-flex items-center gap-2 px-3 py-1.5 border border-white/8 rounded-full mb-6">
              <Shield size={12} className="text-[#b5ff4d]" />
              <span className="text-[10px] uppercase tracking-widest text-zinc-500">Privacy & Data Protection</span>
            </div>
            <h1
              style={{ fontFamily: "var(--font-dm-serif-display), serif" }}
              className="text-[2.2rem] md:text-[2.8rem] font-normal leading-tight mb-3"
            >
              Privacy Policy
            </h1>
            <p className="text-zinc-500 text-sm max-w-xl leading-relaxed">
              This policy explains how FORKSAI collects, uses, and protects your information across the platform - including the study dashboard, AI tools, and payment features.
            </p>
            <p className="text-xs text-zinc-700 mt-3 uppercase tracking-widest">Last updated: June 9, 2026 · v12.1</p>
          </motion.div>

          {/* Two-column layout */}
          <div className="grid md:grid-cols-[200px_1fr] gap-12">

            {/* Sticky sidebar TOC */}
            <aside className="hidden md:block">
              <div className="sticky top-28">
                <p className="text-[9px] uppercase tracking-[0.25em] text-zinc-700 mb-4">On this page</p>
                <ul className="space-y-2">
                  {sections.map(s => (
                    <li key={s.id}>
                      <a
                        href={`#${s.id}`}
                        className="text-xs text-zinc-600 hover:text-[#b5ff4d] transition-colors leading-relaxed block"
                      >
                        {s.title}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>
            </aside>

            {/* Content */}
            <div className="divide-y divide-white/5">
              {sections.map((section, i) => (
                <motion.section
                  key={section.id}
                  id={section.id}
                  initial={{ opacity: 0, y: 12 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ duration: 0.4, delay: 0.05 }}
                  className="scroll-mt-28 py-10 first:pt-0"
                >
                  <div className="flex items-start gap-4 mb-4">
                    <span className="text-[10px] font-mono text-zinc-700 pt-1 w-6 shrink-0">
                      {String(i + 1).padStart(2, "0")}
                    </span>
                    <h2
                      style={{ fontFamily: "var(--font-dm-serif-display), serif" }}
                      className="text-xl font-normal text-white"
                    >
                      {section.title}
                    </h2>
                  </div>
                  <div className="ml-10 text-zinc-400 leading-relaxed">
                    {section.content}
                  </div>
                </motion.section>
              ))}
            </div>
          </div>
        </div>

        {/* Footer strip */}
        <div className="border-t border-white/5 px-6 md:px-12 py-8 mt-8">
          <div className="max-w-6xl mx-auto flex flex-col md:flex-row items-center justify-between gap-3 text-xs text-zinc-700">
            <span>© {new Date().getFullYear()} FORKSAI. All rights reserved.</span>
            <div className="flex items-center gap-5">
              <a href="/terms" className="hover:text-white transition-colors">Terms</a>
              <a href="mailto:support@forksai.app" className="hover:text-white transition-colors">Contact</a>
              <a href="/refund-policy" className="hover:text-white transition-colors">Refund Policy</a>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
